export const SilderChosse = [
    {
      id: 1,
      title: "Luke & Liam Spiteri",
      date: "2024-04-18",
      description: "Had a great experience with the team at Promoti and they were able to get the job done on time and were great on pricing and communication. Thanks again guys",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 2,
      title: "Jordan Saliba",
      date: "2024-04-18",
      description: "Great price and turnaround on my mesh banners for my job site and on A-frames too! Very easy to deal with and highly recommend. Thanks again boys!",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 3,
      title: "Nick Patterson",
      date: "2024-04-18",
      description: "Promoti have been amazing! Quality products, fast turnarounds and a great team to work with! Highly recommend!",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 4,
      title: "Lucas Murana",
      date: "2024-04-18",
      description: "Very Understanding, very easy to work with, lovely group on top of that, definitely would recommend them to any company",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 5,
      title: "Anthony Tahche",
      date: "2024-04-18",
      description: "Very Understanding, very easy to work with, lovely group on top of that, definitely would recommend them to any company",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 6,
      title: "maddisonnx",
      date: "2024-04-18",
      description:"Promoti were very responsive and easy to work with. Attention to detail was super high and a lot of care was taken when printing my wedding invitations, envelopes and RSVP cards, making sure the right quantities and paper types were ordered. They also were able to get me the best deal I hadn’t seen anywhere else! Thanks!",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
    {
      id: 7,
      title: "Lucas Murana",
      date: "2024-04-18",
      description: "Very Understanding, very easy to work with, lovely group on top of that, definitely would recommend them to any company",
      img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
    },
  ];